- hosts: test-server
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: install maven
      apt:
        pkg: maven
        state: present

    - name: install docker
      apt:
        pkg: docker.io
        state: present

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Medicure app deployemnt to test server
      command: docker run -itd -p 8082:8082 subhasnongthombam/medicure:1.0
